sudo: required
services: docker
language: bash
env:
    global:
        - QEMU_VER=v2.9.1
        - DOCKER_REPO=maartje/etcd-multiarch
    matrix:
        - ARCH=amd64    VERSION=v3.2.6    QEMU_ARCH=x86_64
        - ARCH=armhf    VERSION=v3.2.6    QEMU_ARCH=arm
        - ARCH=arm64    VERSION=v3.2.6    QEMU_ARCH=aarch64

before_script:
    - sudo apt-get -y install qemu-user-static
    - docker run --rm --privileged multiarch/qemu-user-static:register
script:
    - sudo ./update.sh --arch ="$ARCH" --version ="$VERSION" --qemuarch="$QEMU_ARCH" --qemuversion="$QEMU_VER" --repo="$DOCKER_REPO"
after_success:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push $DOCKER_REPO
